all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/task-app.pem

  children:
    frontend:
      hosts:
        frontend-dev:
          ansible_host: 54.195.109.1
    
    backend: 
      hosts:
        backend-dev:
          ansible_host: 3.254.119.240
