all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/task-app.pem

  children:
    frontend:
      hosts:
        frontend-dev:
          ansible_host: 108.131.85.44
    
    backend: 
      hosts:
        backend-dev:
          ansible_host: 34.243.47.255
