backend_runtime: python3
backend_port: 5000
backend_app_dir: "{{ app_base_dir }}/backend"
backend_venv_dir: "{{ backend_app_dir }}/venv"
backend_runtime_packages:
  - python3
  - python3-venv
  - python3-pip
  - postgresql-client
  - nginx
  - certbot
  - python3-certbot-nginx

db_name: taskapp
db_user: taskapp_user
db_port: 5432
db_host: "{{ terraform_output.db_endpoint.value }}"
db_password: "{{ vault_db_password }}"
backend_repo_url: https://github.com/onlydurodola/taskapp_backend.git
backend_branch: main
backend_gunicorn_workers: 2
backend_bind_address: 0.0.0.0:5000
